os: linux
services:
  - xvfb
language: node_js
node_js:
  - "10"
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
  npm run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $github_access_token
  keep-history: true
  local-dir: public
  on:
    branch: master
